import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import axios from "axios";
import Script from "next/script";

const merchantPublicKey = "pub_sandbox_N3JQzyuR.VXjgMrW90DWWfwbd2eerxDA3mSG7uVdR";
const mandoPublicKey = 'pub_sandbox_96qsBHrP.IIVG6xPaGkLIneXeekspk9muIAfYaesn'

export default function Home() {

    const [orderId, setOrderId] = useState(); // order id from create order
    const [orderLoading, setOrderLoading] = useState(false);


    // Creating an order https://developers.holacash.mx/openapi/cash/#tag/order
    const generateOrder = async () => {
        setOrderLoading(true);
        try {
            const response = await axios.post(
                "https://sandbox.api.holacash.mx/v2/order",
                {
                    order_total_amount: {
                        amount: 450,
                        currency_code: "MXN",
                    },
                    description: "Pizza",
                },
                {
                    headers: {
                        "X-Api-Client-Key": merchantPublicKey,
                        "Content-Type": "application/json",
                    },
                }
            );

            setOrderLoading(false);

            // verifying correct response from create order
            if (response?.data?.order_information?.order_id) {
                setOrderId(response?.data?.order_information?.order_id);
                console.log("ORDER ID:", response?.data?.order_information?.order_id);
                const callbacks = {
                    onSuccess: (res) => {
                        console.log('onSuccess', JSON.parse(res))
                    },
                    onAbort: () => console.log('onAbort callback'),
                    onError: (err) => console.log(JSON.stringify(err))
                };

                // Initializing widget with order information
                // eslint-disable-next-line no-undef
                HolaCashCheckout.configure(
                    { order_id: response?.data?.order_information?.order_id },
                    callbacks
                );
            }
        } catch {
            setOrderLoading(false);
        }
    };

    return (
        <div className="App">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script
                    async
                    src="https://widget.connect.sandbox.holacash.mx/connect.min.js"
                    id="holacash-connect"
                    type="text/javascript"
                    data-public-key="pub_sandbox_96qsBHrP.IIVG6xPaGkLIneXeekspk9muIAfYaesn"
                > </script>
            </Head>
            <button onClick={() => generateOrder()}>
                Pagar
            </button>
            {/* Creating Button object  */}
            <div id="instant-holacash-checkout-button">
                {!orderLoading && orderId ? (
                    <object
                        id="checkout-button"
                        data={`https://sandbox.api.holacash.mx/v2/checkout/button?public_key=${merchantPublicKey}`}
                    />
                ) : null}
            </div>
        </div>
    );

}
